### PR TITLE
Fix handling of project that contain a space in their path

### LINKED ISSUE #29: JetbrainsRunner opens an empty file instead of project
I installed the last version of JetbrainsRunner 1.9.1, it finds the recent projects but each time it opens a blank file with the name of the project in LightEdit Mode, instead of opening the project. This behavior is for all the Jetbrains apps I tested (Pycharm Pro, IntelliJ Pro, Webstorm), all installed with Toolbox.

image

I am on EndeavourOS KDE.

Any solution for this ?

Thanks.

### PR DESCRIPTION
**Pull request by alex1701c**
We need to properly escape the path, otherwise it gets interpreted as two arguments.

Fixes https://github.com/alex1701c/JetBrainsRunner/issues/29

### CODE REVIEW

**Comment by alex1701c** [comment]
@ gschurck Can you please try this out? 

Maybe do `git pull --recurse-submodules` to ensure that the submodule is updated too.

**Comment by alex1701c** [comment]
@gschurck Can you please try this out?

Maybe do git pull --recurse-submodules to ensure that the submodule is updated too.

**Comment by gschurck** [comment]
So the issue was from the space in the directory's name ? I knew it was a bad idea lol.

I have this error when running install.sh
```
CMake Error at src/CMakeLists.txt:3 (add_subdirectory):
  The source directory

    /home/guillaume/repos/JetBrainsRunner/src/jetbrains-api

  does not contain a CMakeLists.txt file.
```

**Comment by gschurck** [comment]
So the issue was from the space in the directory's name... I knew it was a bad idea lol.

I can confirm it works for me.
Thank you !

**Comment by alex1701c** [comment]
Thanks for confirming the fix and the fast feedback!

I will make a new release & update it on https://www.pling.com/p/1311630/.

**Pull request merged**
